Refactor getting default locations data
ximet/ReactTask pull request #125
Opened 2021-10-26 12:33 UTC by JaneEllison

2021-10-26 13:24 UTC, anton-vlasik commented on src/redux/actions/initAppActions.js
> +  const cityInfos = await Promise.all(cityInfoPromises);
TBH I doubt that info has plural form

2021-10-26 14:02 UTC, JaneEllison commented on src/redux/actions/initAppActions.js
> +  const cityInfos = await Promise.all(cityInfoPromises);
Corrected to "citiesInfo"

2021-10-27 11:06 UTC, anton-vlasik approved these changes

2021-10-27 11:07 UTC, anton-vlasik commented on src/redux/actions/initAppActions.js
> +    dispatch(setRecentCity(info));
could you set all info all together?

2021-10-27 11:07 UTC, anton-vlasik requested changes
you need to resolve conflicts

2021-10-27 12:10 UTC, JaneEllison commented on src/redux/actions/initAppActions.js
> +    dispatch(setRecentCity(info));
do you mean do something like this: 

 `dispatch(setRecentCity(citiesInfo ));` ?

no, i could't because when I set new City I call function which check is this sity already in recentCities state and if I pass an array there i need to pass array of one city later to add new city, and loop over this array to check is this city already exist

2021-10-27 13:06 UTC, anton-vlasik commented on src/redux/actions/initAppActions.js
> +    dispatch(setRecentCity(info));
It would make things more optimised though. To loop through array in your function vs. dispatch actions in a loop.

2021-10-27 13:06 UTC, anton-vlasik approved these changes

2021-10-27 13:06 UTC, merged